alias ls='ls --color=auto' 
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color'

export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\]\[\033[0;35m\]`__git_ps1`\[\033[00m\] \$ '

export LANGUAGE=C.UTF-8
export LANG=C.UTF-8
export LC_ALL=C.UTF-8

export GOROOT=/usr/local/go
export GOPATH=$HOME
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
